name: Publish to AUR

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest -q

  publish:
    needs: test
    runs-on: ubuntu-latest
    env:
      AUR_PACKAGE_NAME: aur-init
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate .SRCINFO in Arch container
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            set -euo pipefail
            pacman -Syu --noconfirm base-devel git
            makepkg --printsrcinfo > .SRCINFO

      - name: Set up SSH for AUR
        shell: bash
        env:
          AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          echo "$AUR_SSH_PRIVATE_KEY" > ~/.ssh/aur
          chmod 600 ~/.ssh/aur
          ssh-keyscan -t rsa aur.archlinux.org >> ~/.ssh/known_hosts
          cat >> ~/.ssh/config <<EOF
          Host aur.archlinux.org
            HostName aur.archlinux.org
            User aur
            IdentityFile ~/.ssh/aur
          EOF

      - name: Sync packaging files to AUR repo
        shell: bash
        run: |
          set -euo pipefail
          rm -rf aur-pkg
          git clone ssh://aur@aur.archlinux.org/${AUR_PACKAGE_NAME}.git aur-pkg
          rsync -a --delete \
            --include 'PKGBUILD' \
            --include '.SRCINFO' \
            --include '*.install' \
            --exclude '*' \
            ./ aur-pkg/
          cd aur-pkg
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git status --porcelain | grep .; then
            git add -A
            git commit -m "chore(aur): update PKGBUILD and .SRCINFO from ${GITHUB_SHA::7}"
            git push origin HEAD:master
          else
            echo "No changes to publish."
          fi
