name: Tests & Coverage

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: write  # required to commit the coverage badge

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage
          # Try genbadge with extras, fall back to base package
          pip install 'genbadge[all]' || pip install genbadge
          pip show genbadge || true

      - name: Run tests with coverage
        run: |
          pytest \
            --cov=lib \
            --cov-branch \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml \
            --cov-fail-under=65

      - name: Generate coverage badge (if available)
        run: |
          python - <<'PY'
          import importlib, sys, subprocess
          try:
              importlib.import_module('genbadge.coverage')
          except Exception:
              print('genbadge not available; skipping badge generation', file=sys.stderr)
              sys.exit(0)
          subprocess.check_call([sys.executable, '-m', 'genbadge.coverage', '-i', 'coverage.xml', '-o', 'coverage-badge.svg'])
          PY

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
          if-no-files-found: ignore

      - name: Commit coverage badge
        if: ${{ hashFiles('coverage-badge.svg') != '' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ci): update coverage badge"
          file_pattern: coverage-badge.svg
